### ISSUE TITLE
Clarify which OS is really supported

### ISSUE THREAD

**Issue by BenoitPoulet** [ConSol-Monitoring/snclient#48]
Hello,

Can you specify on the documentation which OS is really supported ?

I tried to to install the .deb packages on :
Debian 5 - failed
Debian 6 - failed
Debian 7 - failed
Debian 8 - failed
Debian 9 - failed
Debian 10 - failed

```
# dpkg -i snclient-0.08-linux-amd64.deb
dpkg-deb: error: archive 'snclient-0.08-linux-amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive snclient-0.08-linux-amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 snclient-0.08-linux-amd64.deb
```

I think the question is the same for RPM on Linux and Windows (I tried on 2019, it works)

Thanks.
Regards.

**Comment by BenoitPoulet** [comment]
Indeed.

So we have 2 points here
- deb can’t be installed on theses distro, but perhaps it’s wanted.
- my question is still relevant as there is no info about which distro version is supported.

**Comment by sni** [comment]
right now there is no such list, simply because i didn't have time for it. So at the moment we support whatever our customers need, which are mainly newer linux/windows systems like centos 7, debian 11, windows 10 and newer.
The agent should probably run on those older systems, but the packaging won't work. Also i haven't added anything except systemd and windows service integration for now.
In case the binary does not work, you have to rebuild it manually as described in https://omd.consol.de/docs/snclient/install/build/

In case you want to dig into this, i am happy to accept pull requests which make the packing more backward compatible.

**Comment by BenoitPoulet** [comment]
Thank you for your answer.
I close.

**Comment by sni** [comment]
Also started a page here: https://omd.consol.de/docs/snclient/install/supported/ to list known working systems.
