### ISSUE TITLE
Service check shows ok if Service is stopped or disabled - Windows services

### ISSUE THREAD

**Issue by kafos** [ConSol-Monitoring/snclient#72]
If I understand correctly, then I should get a warning/critical, if a service is disabled in windows.
a filter like "service=SERVICENAME" should be enough.
I get:
![image](https://github.com/ConSol-Monitoring/snclient/assets/29919422/0ab053ac-143f-4e9d-b904-9de663ca385a)

how the query should look like with nrpe, if I want to get a warning if service is stopped?
check_nrpe -H [IP] -c check_service -a 'service=CpdService' ...
tried different variations but the query seems to be not korrekt

**Comment by sni** [comment]
i see, the issue here is the default warning/condition is "state != 'running' && start_type = 'auto'" which then fails to an issue if the start type does not match.
This should be fixed with f62dd7bbe7bbb35d7e8cee613c1b921cbdf8c2c7. Default filters are now adjusted if service=... is used and only the state condition remains.
